### PR TITLE
Fix font

### PR DESCRIPTION
**Pull request by kelvinsekx**

### CODE REVIEW

**Comment by WojuadeAA** [comment]
The padding is still not showing

**Comment by kelvinsekx** [comment]
wawu

**Comment by kelvinsekx** [comment]
It is crazy because everything works fine on my end

**Comment by kelvinsekx** [comment]
can you share a record of your screen with me on whatsapp?

**Comment by WojuadeAA** [comment]
sure will do

**Review by WojuadeAA — APPROVED** [review]

**Pull request merged**
