### PR TITLE
Fixing line spacing overlap on smaller devices in the footer and  making ui changes to the FAQ components

### PR DESCRIPTION
**Pull request by dLuxKid**
Hello Bad Techies,

I hope this message finds you well. I wanted to bring your attention to an issue I encountered while using the project on smaller devices(my iPhone 7 to be specific) and the corresponding solution I have implemented in my pull request.

On smaller devices, when the text content wraps to the next line, the line spacing becomes a little overlapped, resulting in a visually messy appearance and reduced readability. To address the issue, I increase the line spacing on the 'p' tag in the footer. 

The FAQ question icon, I thought a little animation could spice up the UI. so I rotated the icon 180 degree wise when clicked. 

I have submitted a pull request that contains the necessary code changes to resolve the line spacing overlap and the animation in the FAQ question icon. 

Thank you for your time and consideration.

Best regards,
Marvellous

### CODE REVIEW

**Comment by kelvinsekx** [comment]
Thanks @dLuxKid ,
Can you share a screenshot of before and after your changes?

And thanks for helping us improve Ibadan Techies ❤️

**Comment by dLuxKid** [comment]
IMG_4861
IMG_4864
IMG_4863

These are the changes made

**Comment by dLuxKid** [comment]
> IMG_4861 IMG_4864 IMG_4863
> 
> These are the changes made

The first image shows how the footer text looked on my screen, the second screen shows the change i made to the FAQ icon when clicked, the third images shows the text on the footer after increasing the line spacing

**Review by kelvinsekx — APPROVED** [review]

**Comment by kelvinsekx** [comment]
Hey @dLuxKid ,
Thanks for your changes...🚀

**Pull request merged**
