### PR TITLE
Reworking seo content

### PR DESCRIPTION
**Pull request by kelvinsekx**

### CODE REVIEW

**Comment by kelvinsekx** [comment]
## screenshots of where I made changes to content
I personally feel this is only a 1/3 change intended. I'll add the rest after getting your feedbacks.

seo3
seo2
seo1
seo4

**Comment by WojuadeAA** [comment]
Which issue does this close? 🤔

**Comment by kelvinsekx** [comment]
> Which issue does this close? 🤔

OMG I didn't create an issue for it o. Can you do that?

**Comment by kelvinsekx** [comment]
Also if you merge this PR before the second one on test (there are two PRs now), you might not need to merge the other one because this branch was forked from that one.

**Comment by kelvinsekx** [comment]
## I made a new commit that adds upto a 70% use of the keywords.
seo5

**Review by WojuadeAA — APPROVED** [review]
closes #121

**Pull request merged**
